# Generated by Django 6.1 on 2026-09-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_compteutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Marchandise',
                'verbose_name_plural': 'Marchandises',
                'ordering': ['nom'],
            },
        ),
    ]
