# Generated by Django 6.1 on 2026-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_marchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WAGON', 'Wagon'), ('CONTENEUR', 'Conteneur')], max_length=20)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_UTILISATION', 'En utilisation')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'verbose_name': 'Moyen de transport',
                'verbose_name_plural': 'Moyens de transport',
                'ordering': ['numero'],
            },
        ),
    ]
