# Generated by Django 6.1 on 2026-09-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_moyentransport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(blank=True, max_length=50, unique=True)),
                ('type', models.CharField(choices=[('D15', 'D15'), ('TITRE_PROVENANCE', 'Titre de provenance')], max_length=20)),
                ('provenance', models.CharField(max_length=100)),
                ('volume_total_autorise', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_total_restant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EPUISE', 'Épuisé')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'categorie': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='transit.tiers')),
                ('marchandise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='transit.marchandise')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-id'],
            },
        ),
    ]
