# Generated by Django 6.1 on 2026-09-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteutilisateur',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('AGENT_TRANSIT', 'Agent de transit'), ('CHEF_DEPOT', 'Chef de dépôt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EPUISE', 'Épuisé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
