# Generated by Django 6.1 on 2026-10-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_alter_compteutilisateur_role_alter_contrat_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lettre_voiture', models.CharField(blank=True, max_length=50, unique=True)),
                ('numero_bl', models.CharField(max_length=50)),
                ('trajet', models.CharField(max_length=255)),
                ('date_arrivee', models.DateField()),
                ('chauffeur', models.CharField(max_length=255)),
                ('immatriculation_camion', models.CharField(max_length=50)),
                ('pays_provenance', models.CharField(max_length=100)),
                ('chargeur', models.ForeignKey(limit_choices_to={'categorie': 'CHARGEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='lettres_voiture_chargeur', to='transit.tiers')),
                ('client', models.ForeignKey(limit_choices_to={'categorie': 'CLIENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='lettres_voiture_client', to='transit.tiers')),
                ('transporteur', models.ForeignKey(limit_choices_to={'categorie': 'TRANSPORTEUR'}, on_delete=django.db.models.deletion.PROTECT, related_name='lettres_voiture_transporteur', to='transit.tiers')),
            ],
            options={
                'verbose_name': 'Lettre de voiture',
                'verbose_name_plural': 'Lettres de voiture',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bille', models.CharField(max_length=50)),
                ('longueur', models.DecimalField(decimal_places=2, max_digits=6)),
                ('diametre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualite', models.CharField(blank=True, max_length=100)),
                ('contrat', models.ForeignKey(limit_choices_to={'statut': 'ACTIF'}, on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='transit.contrat')),
                ('marchandise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='transit.marchandise')),
                ('lettre_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='transit.lettrevoiture')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-id'],
            },
        ),
    ]
