# Generated by Django 6.1 on 2026-10-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_lettrevoiture_colis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='diametre',
            field=models.DecimalField(decimal_places=2, help_text='En mètres', max_digits=6),
        ),
        migrations.AlterField(
            model_name='colis',
            name='longueur',
            field=models.DecimalField(decimal_places=2, help_text='En mètres', max_digits=6),
        ),
        migrations.AlterField(
            model_name='colis',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En m³, calculé automatiquement', max_digits=10),
        ),
    ]
