# Generated by Django 6.1 on 2026-10-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_alter_colis_diametre_alter_colis_longueur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='qualite',
        ),
    ]
