# Generated by Django 6.1 on 2026-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0009_remove_colis_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettrevoiture',
            name='bordereau',
            field=models.FileField(blank=True, null=True, upload_to='bordereaux/'),
        ),
        migrations.AddField(
            model_name='lettrevoiture',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lettrevoiture',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CLOTURE', 'Clôturé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
