# Generated by Django 6.1 on 2026-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0010_lettrevoiture_bordereau_lettrevoiture_date_cloture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettrevoiture',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CLOTURE', 'Clôturé'), ('EN_ATTENTE_APPROBATION', "En attente d'approbation")], default='EN_ATTENTE', max_length=25),
        ),
    ]
